# Generated by Django 5.2 on 2025-04-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_d', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='oldorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='OldOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
